routes/web.php
<?php

//Rotas de início
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Rotas autenticadas
Route::group(['middleware' => 'auth'], function()
{
    /* ROTA: ANIMAIS
    * animais => POST(store), GET(index) 
    * animais/create => GET(create) 
    * animais/{id} => PUT(update)
    */
    Route::resource('animal', 'Animal\AnimalController')->except(['show', 'edit', 'destroy']);
    /* ROTA: FAZENDAS
    * fazendas => POST(store), GET(index) 
    * fazendas/create => GET(create) 
    * fazendas/{id} => DELETE(destroy)
    */ 
    Route::resource('fazenda', 'Fazenda\FazendaController')->except(['edit', 'show', 'destroy']);

    /* ROTA: TERRA
    * terra => POST(store), GET(index) 
    * terra/create => GET(create) 
    * terra/{id} => PUT(update)
    */
    Route::resource('terra', 'Insumo\TerraController')->except(['edit', 'show', 'destroy']);

    /* ROTA: FUNCIONARIO
    * funcionario => POST(store), GET(index) 
    * funcionario/create => GET(create) 
    * funcionario/{id} => GET(show), PUT(update), DELETE(destroy)
    * funcionario/{id}/edit => GET(edit)
    */
    Route::resource('funcionario', 'Funcionario\FuncionarioController')->except(['edit', 'destroy', 'show']);

 
    /* ROTA: FUNCIONARIO
    * funcionario => POST(store), GET(index) 
    * funcionario/create => GET(create) 
    * funcionario/{id} => PUT(update)
    */
    Route::resource('fornecedor', 'FornecedorController')->except(['edit', 'destroy', 'show']);
   
    /* ROTA: INSUMO
    * insumo => POST(store), GET(index) 
    * insumo/create => GET(create) 
    * insumo/{id} => PUT(update)
    */
    Route::resource('insumo', 'Insumo\InsumoController')->except(['edit', 'show', 'destroy']);

    /* ROTA: TIPO INSUMO
    * tipoinsumo => POST(store), GET(index) 
    * tipoinsumo/create => GET(create) 
    * tipoinsumo/{id} => GET(show), PUT(update), DELETE(destroy)
    * tipoinsumo/{id}/edit => GET(edit)
    */
    Route::resource('tipoinsumo', 'Insumo\TipoInsumoController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: GRUPO ANIMAL
    * grupoanimal => POST(store), GET(index) 
    * grupoanimal/create => GET(create) 
    * grupoanimal/{id} => GET(show), PUT(update), DELETE(destroy)
    * grupoanimal/{id}/edit => GET(edit)
    */
    Route::resource('grupoanimal', 'Animal\GrupoAnimalController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: TIPO MEDICAMENTO
    * tipomedicamento => POST(store), GET(index) 
    * tipomedicamento/create => GET(create) 
    * tipomedicamento/{id} => GET(show), PUT(update), DELETE(destroy)
    * tipomedicamento/{id}/edit => GET(edit)
    */
    Route::resource('tipomedicamento', 'Animal\TipoMedicamentoController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: MEDICAMENTO
    * medicamento => POST(store), GET(index) 
    * medicamento/create => GET(create) 
    * medicamento/{id} => PUT(update)
    */
    Route::resource('medicamento', 'Animal\MedicamentoController')->except(['edit', 'show', 'destroy']);

    /* ROTA: MÁQUINA
    * maquina => POST(store), GET(index) 
    * maquina/create => GET(create) 
    * maquina/{id} => PUT(update)
    */
    Route::resource('maquina', 'Maquina\MaquinaController')->except(['edit', 'show', 'destroy']);

    /* ROTA: HISTÓRICO ABASTECIMENTO (para saída de combustível)
    * abastecimento => POST(store), GET(index) 
    * abastecimento/create => GET(create) 
    * abastecimento/{id} => DELETE(destroy)
    */
    Route::resource('abastecimento', 'Maquina\HistoricoAbastecimentoController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO ANIMAL (para saída de medicamento)
    * medicacao => POST(store), GET(index) 
    * medicacao/create => GET(create) 
    * medicacao/{id} => DELETE(destroy)
    */
    Route::resource('medicacao', 'Animal\HistoricoAnimalController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO TERRA (para saída de insumo e uso na terra)
    * plantio => POST(store), GET(index) 
    * plantio/create => GET(create) 
    * plantio/{id} => DELETE(destroy)
    */
    Route::resource('plantio', 'Insumo\HistoricoTerraController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA COMBUSTÍVEL
    * compra-combustivel => POST(store), GET(index) 
    * compra-combustivel/create => GET(create) 
    * compra-combustivel/{id} => DELETE(destroy)
    */
    Route::resource('compra-combustivel', 'Maquina\HistoricoCompraCombustivelController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA INSUMO
    * compra-insumo => POST(store), GET(index) 
    * compra-insumo/create => GET(create) 
    * compra-insumo/{id} => DELETE(destroy)
    */
    Route::resource('compra-insumo', 'Insumo\HistoricoCompraInsumoController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA MEDICAMENTO
    * compra-medicamento => POST(store), GET(index) 
    * compra-medicamento/create => GET(create) 
    * compra-medicamento/{id} => DELETE(destroy)
    */
    Route::resource('compra-medicamento', 'Animal\HistoricoCompraMedicamentoController')->except(['show', 'update', 'edit']);

    /* ROTA: COMBUSTÍVEL
    * combustivel => POST(store), GET(index) 
    * combustivel/create => GET(create) 
    * combustivel/{id} => DELETE(destroy)
    */
    Route::resource('combustivel', 'Maquina\CombustivelController')->except(['show', 'update', 'destroy', 'edit']);
    
    /* ROTA: REVISÃO
    * revisao => POST(store), GET(index) 
    * revisao/create => GET(create) 
    * revisao/{id} => DELETE(destroy)
    */
    Route::resource('revisao', 'Maquina\HistoricoRevisaoController')->except(['show', 'update', 'edit']);
});

app/Models/Animal/Animal.php
<?php 

namespace App\Models\Animal;

use Illuminate\Database\Eloquent\Model;

class Animal extends Model
{
    protected $fillable = [
        'id_grupo_animal', 'nome', 'id_fazenda', 'entrada', 'nascimento', 'nome_mae', 'nome_pai'
    ];
    protected $table = 'animal';
    protected $append = ['entrada_convert', 'nascimento_convert'];

    public function Fazenda()
    {
        return $this->belongsTo(\App\Models\Fazenda\Fazenda::class, 'id_fazenda');
    }
    public function GrupoAnimal()
    {
        return $this->belongsTo(GrupoAnimal::class, 'id_grupo_animal');
    }
    public function HistoricoAnimal()
    {
        return $this->hasMany(HistoricoAnimal::class, 'id_animal');
    }

    //Atributos    
    public function getentradaconvertAttribute() {
       return \Carbon\Carbon::parse($this->entrada)->format('d/m/Y');
    }
    public function getnascimentoconvertAttribute() {
        if($this->nascimento)
            return \Carbon\Carbon::parse($this->nascimento)->format('d/m/Y');
        else
            return null;
    }
}

resources/views/pesquisa/panimal.blade.php
@extends('layouts.layout') @section('content')

<div class="container">
	<div class="row pad-botm">
		<div class="col-md-12">
			<h3 class="header-line">Animais</h3>
			@if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif @if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Salvo!</strong> Os dados foram salvos.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">

					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								<tr>
									<th>Nome</th>
									<th>Grupo</th>
									<th>Fazenda</th>
									<th>Entrada</th>
									<th>Nascimento</th>
									<th>Editar</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($animais as $animal)
								<tr class='gradeA'>
									<td> {{$animal->nome}} </td>
									<td> {{$animal->GrupoAnimal->nome}} </td>
									<td> {{$animal->Fazenda->nome}} </td>
									<td> {{$animal->entradaconvert}} </td>
									<td> {{$animal->nascimentoconvert}} </td>
									<td>
										<center>
											<button type="button" class="btn btn-xs btn-warning" onclick="editarAnimal()" data-toggle="modal" data-target="#exampleModal"
											    data-nome="{{$animal->nome}}" data-id="{{$animal->id}}" data-nomemae="{{$animal->nome_mae}}" data-nomepai
											    "{{$animal->nome_pai}}" data-nascimento="{{$animal->nascimento}}" data-grupoanimal="{{$animal->id_grupo_animal}}" data-entrada="{{$animal->entrada}}"
											    data-fazenda="{{$animal->id_fazenda}}" data-route="animal">Editar</button>
										</center>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>
					</div>

					<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
									<h4 class="modal-title" id="exampleModalLabel">Editar</h4>
								</div>
								<div class="modal-body">

									@if(isset($animal))
									<form id="editar" name="update-animal" method='POST'>
										{{ csrf_field() }} {{ method_field('PUT') }}
										<div class="panel-body">
											<div class="row">

												<div class="col-md-8">
													<div class="form-group">
														<label>Fazenda:</label>
														<select class="form-control" required id="fazenda" name="id_fazenda" /> @foreach($fazendas as $fazenda)
														<option value="{{$fazenda->id}}">{{$fazenda->nome}}</option>
														@endforeach
														</select>
													</div>

													<div class="form-group">
														<label>Nome:</label>
														<input class="form-control" id="nome" required name="nome" type="text" placeholder="Identificação do animal" maxlength="45"
														/>
													</div>

													<div class="form-group">
														<label>Grupo do animal:</label>
														<select class="form-control" id="grupoanimal" required name="id_grupo_animal">
															@foreach($grupos as $item)
															<option value="{{$item->id}}">{{$item->nome}}</option>
															@endforeach
														</select>
													</div>

													<div class="form-group">
														<label>Data de entrada:</label>
														<input class="form-control" id="entrada" required name="entrada" type="date" placeholder="DD/MM/AAAA" maxlength="45" value="{{ old('entrada')}}"
														/>
													</div>

													<div class="form-group">
														<label>Data de Nascimento:</label>
														<input class="form-control" id="nascimento" name="nascimento" type="date" placeholder="DD/MM/AAAA" maxlength="45" value="{{ old('nascimento')}}"
														/>
													</div>

													<div class="form-group">
														<label>Mãe:</label>
														<input class="form-control" id="nomemae" name="nome_mae" type="text" placeholder="Identificação da mãe" maxlength="45" value="{{ old('nome_mae')}}"
														/>
													</div>

													<div class="form-group">
														<label>Pai:</label>
														<input class="form-control" id="nomepai" name="nome_pai" type="text" placeholder="Identificação do pai" maxlength="45" value="{{ old('nome_pai')}}"
														/>
													</div>
												</div>
											</div>
										</div>
										<div class='modal-footer'>
											<button type='button' class='btn btn-danger' data-dismiss='modal'>Cancelar</button>
											<button type='submit' class='btn btn-primary'>Editar</button>
										</div>
									</form>
									@endif

								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
</div>
</div>
</div>

@endsection

resources/views/pesquisa/pcombustivel.blade.php
@extends('layouts.layout') @section('content')
<div class="container">
	<div class="row pad-botm">
		<div class="col-md-12">
			<h3 class="header-line">Combustível</h3>
			@if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif @if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Salvo!</strong> Os dados foram salvos.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">

					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								<tr>
									<th>Fazenda</th>
									<th>Estoque (Diesel)</th>
								</tr>
							</thead>
							<tbody>
								@if(isset($combustiveis)) @foreach ($combustiveis as $combustivel)
								<tr class='gradeA'>
									<td> {{$combustivel->Fazenda->nome}} </td>
									<td> {{$combustivel->quantidade}} </td>
								</tr>
								@endforeach @endif
							</tbody>
						</table>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
</div>
</div>
</div>

@endsection

resources/views/pesquisa/pfarmacia.blade.php
@extends('layouts.layout') @section('content')
<div class="container">
	<div class="row pad-botm">
		<div class="col-md-12">
			<h3 class="header-line">Medicamentos</h3>
			@if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif @if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Salvo!</strong> Os dados foram salvos.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="table-responsive">

						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								<tr>
									<th>Fazenda</th>
									<th>Nome</th>
									<th>Tipo</th>
									<th>Estoque</th>
									<th>Editar</th>
								</tr>
							</thead>
							<tbody>
								@if(isset($medicamentos)) @foreach ($medicamentos as $medicamento)
								<tr class='gradeA'>
									<td> {{$medicamento->Fazenda->nome}} </td>
									<td> {{$medicamento->nome}} </td>
									<td> {{$medicamento->TipoMedicamento->nome}} </td>
									<td> {{$medicamento->quantidade}} </td>
									<td>
										<center>
											<button type="button" class="btn btn-xs btn-warning" onclick="editarMedicamento()" data-toggle="modal" data-target="#exampleModal"
											    data-nome="{{$medicamento->nome}}" data-id="{{$medicamento->id}}" data-fazenda="{{$medicamento->id_fazenda}}"
											    data-tipo="{{$medicamento->id_tipo_medicamento}}" data-obs="{{$medicamento->obs}}" data-route="medicamento">Editar</button>
										</center>
									</td>
								</tr>
								@endforeach @endif
							</tbody>
						</table>

					</div>

					<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
									<h4 class="modal-title">Editar</h4>
								</div>
								<div class="modal-body">
									@if(isset($medicamento))
									<form id="editar" name='update-medicamento' method='POST'>
										{{ csrf_field() }} {{ method_field('PUT') }}
										<div class="panel-body">

											<div class="row">
												<div class="col-md-8">
													<div class="form-group">
														<label>Fazenda:</label>
														<select class="form-control" required id="fazenda" name="id_fazenda">
															@foreach($fazendas as $fazenda) 
															<option value="{{$fazenda->id}}">{{$fazenda->nome}}</option>
															@endforeach
														</select>
													</div>
												</div>
											</div>

											<div class="row">
												<div class="col-md-8">
													<div class="form-group">
														<label>Tipo de Medicamento:</label>
														<select class="form-control" required id="tipo" name="id_tipo_medicamento">
															@foreach($tipos as $tipo) 
															<option value="{{$tipo->id}}">{{$tipo->nome}}</option>
															@endforeach
														</select>
													</div>
												</div>
											</div> 

											<div class="row">
												<div class="col-md-8">
													<div class="form-group">
														<label>Nome:</label>
														<input class="form-control" id="nome" required name="nome" type="text"
														placeholder="Nome da máquina" maxlength="45"/>
													</div>
												</div>
											</div>

											<div class="row"> 
												<div class="col-md-12">
													<div class="form-group">
														<label>Obs.:</label>
														<textarea class="form-control" id="obs" required style="resize: vertical" name="obs"
														maxlength="140" placeholder="Observações sobre o medicamento"></textarea>
													</div>
												</div>
											</div>

										</div>
										<div class='modal-footer'>
											<button type='button' class='btn btn-danger' data-dismiss='modal'>Cancelar</button>
											<button type='submit' class='btn btn-primary'>Editar</button>
										</div>
									</form>
									@endif

								</div>
							</div>
						</div>
					</div>

				</div>
			</div>
		</div>
	</div>
</div>
</div>
</div>
</div>

@endsection

resources/views/pesquisa/pfazenda.blade.php
@extends('layouts.layout') @section('content')
<div class="container">
	<div class="row pad-botm">
		<div class="col-md-12">
			<h3 class="header-line">Fazendas</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Salvo!</strong> Os dados foram salvos.
			</div>
			@endif @if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="table-responsive">

						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								<tr>
									<th>Nome</th>
									<th>Localidade</th>
									<th>Editar</th>
								</tr>
							</thead>
							<tbody>
								@if(isset($fazendas)) @foreach ($fazendas as $fazenda)
								<tr class='gradeA'>
									<td> {{$fazenda->nome}} </td>
									@if($fazenda->localidade)
									<td> {{$fazenda->localidade}} </td>
									@else
									<td>
										<center>-</center>
									</td>
									@endif
									<td>
										<center>
											<button type="button" class="btn btn-xs btn-warning" onclick="editarFazenda()" data-toggle="modal" data-target="#exampleModal"
											    data-nome="{{$fazenda->nome}}" data-id="{{$fazenda->id}}" data-localidade="{{$fazenda->localidade}}" data-route="fazenda">Editar</button>
										</center>
									</td>
								</tr>
								@endforeach @endif

							</tbody>
						</table>

					</div>
				</div>
			</div>

			<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">&times;</span>
							</button>
							<h4 class="modal-title" id="exampleModalLabel">Editar</h4>
						</div>
						<div class="modal-body">

							@if(isset($fazenda))
							<form id="editar" name='update-fazenda' method='POST'>
								{{ csrf_field() }} {{ method_field('PUT') }}

								<div class='panel-body'>
									<div class='row'>
										<div class='col-md-4'>
											<div class="form-group">
												<label>Nome:</label>
												<input class="form-control" required id="nome" name="nome" type="text" maxlength="100" />
											</div>
											<div class="form-group">
												<label>Localidade:</label>
												<input class="form-control" required id="localidade" name="localidade" type="text" maxlength="45" />
											</div>
										</div>
									</div>
								</div>

								<div class='modal-footer'>
									<button type='button' class='btn btn-danger' data-dismiss='modal'>Cancelar</button>
									<button type='submit' class='btn btn-primary'>Editar</button>
								</div>

							</form>
							@endif

						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</div>
</div>
</div>
</div>

@endsection

resources/views/pesquisa/pfornecedor.blade.php
 @extends('layouts.layout') @section('content')
<div class="container">
	<div class="row pad-botm">
		<div class="col-md-12">
			<h3 class="header-line">Fornecedores</h3>
			@if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif @if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Salvo!</strong> Os dados foram salvos.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">

					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								<tr>
									<th>Nome</th>
									<th>Telefone</th>
									<th>Editar</th>
								</tr>
							</thead>
							<tbody>
								@foreach ($fornecedores as $fornecedor)
								<tr class='gradeA'>
									<td> {{$fornecedor->nome}} </td>
									<td> {{$fornecedor->telefone}} </td>
									<td>
										<center>
											<button type="button" class="btn btn-xs btn-warning" onclick="editarFornecedor()" data-toggle="modal" data-target="#exampleModal"
											    data-nome="{{$fornecedor->nome}}" data-id="{{$fornecedor->id}}" data-telefone="{{$fornecedor->telefone}}" data-route="fornecedor">Editar</button>
										</center>
									</td>
								</tr>
								@endforeach
							</tbody>
						</table>

					</div>

					<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
						<div class="modal-dialog" role="document">
							<div class="modal-content">
								<div class="modal-header">
									<button type="button" class="close" data-dismiss="modal" aria-label="Close">
										<span aria-hidden="true">&times;</span>
									</button>
									<h4 class="modal-title" id="exampleModalLabel">Editar</h4>
								</div>
								<div class="modal-body">

									@if(isset($fornecedor))
									<form id="editar" name='update-fornecedor' method='POST'>
										{{ csrf_field() }} {{ method_field('PUT') }}
										<div class="panel-body">
											<div class="row">
												<div class="col-md-12">

													<div class="col-md-8">
														<div class="form-group">
															<label>Nome:</label>
															<input class="form-control" required id="nome" type="text" name="nome" placeholder="Insira aqui o nome do fornecedor" maxlength="45"
															/>
														</div>
													</div>

													<div class="col-md-8">
														<div class="form-group">
															<label>Telefone:</label>
															<input class="form-control" id="telefone" required type="text" name="telefone" placeholder="(__)____-____" maxlength="45" />
														</div>
													</div>
												</div>
											</div>
										</div>
										<div class='modal-footer'>
											<button type='button' class='btn btn-danger' data-dismiss='modal'>Cancelar</button>
											<button type='submit' class='btn btn-primary'>Editar</button>
										</div>
									</form>
									@endif

								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
</div>
</div>
@endsection

resources/views/pesquisa/previsao.blade.php
@extends('layouts.layout') @section('content')
<div class="container">
	<div class="row pad-botm">
		<div class="col-md-12">
			<h3 class="header-line">Pesquisar Revisões</h3>
			@if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<!-- Advanced Tables -->
			<div class="panel panel-default">
				<div class="panel-heading">
					Buscar por Revisões
				</div>
				<div class="panel-body">

					<div class="table-responsive">
						<table class="table table-striped table-bordered table-hover" id="dataTables-example">
							<thead>
								<tr>
									<th>Fazenda</th>
									<th>Máquina</th>
									<th>Funcionário</th>
									<th>Item (Comprado)</th>
									<th>Nota Fiscal</th>
									<th>Valor</th>
									<th>Problema</th>
									<th>Editar</th>
								</tr>
							</thead>
							<tbody>
							@if(isset($revisoes))
								@foreach ($revisoes as $revisao)
								<tr class='gradeA'>
									<td> {{$revisao->Fazenda->nome}} </td>
									<td> {{$revisao->Maquina->nome}} </td>
									<td> {{$revisao->Funcionario->nome}} </td>
									<td> {{$revisao->item}} </td>
									<td> {{$revisao->nota_fiscal}} </td>
									<td> {{$revisao->valor}} </td>
									<td> {{$revisao->problema}} </td>
									<td>  </td>
								</tr>
								@endforeach
							@endif
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>

	</div>
</div>
<!--End Advanced Tables -->
</div>
</div>
</div>

@endsection