routes/web.php
<?php

//Rotas de início
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Rotas autenticadas
Route::group(['middleware' => 'auth'], function()
{
    /* ROTA: ANIMAIS
    * animais => POST(store), GET(index) 
    * animais/create => GET(create) 
    * animais/{id} => PUT(update)
    */
    Route::resource('animal', 'Animal\AnimalController')->except(['show', 'edit', 'destroy']);
    /* ROTA: FAZENDAS
    * fazendas => POST(store), GET(index) 
    * fazendas/create => GET(create) 
    * fazendas/{id} => DELETE(destroy)
    */ 
    Route::resource('fazenda', 'Fazenda\FazendaController')->except(['edit', 'show', 'destroy']);

    /* ROTA: TERRA
    * terra => POST(store), GET(index) 
    * terra/create => GET(create) 
    * terra/{id} => PUT(update)
    */
    Route::resource('terra', 'Insumo\TerraController')->except(['edit', 'show', 'destroy']);

    /* ROTA: FUNCIONARIO
    * funcionario => POST(store), GET(index) 
    * funcionario/create => GET(create) 
    * funcionario/{id} => GET(show), PUT(update), DELETE(destroy)
    * funcionario/{id}/edit => GET(edit)
    */
    Route::resource('funcionario', 'Funcionario\FuncionarioController')->except(['edit', 'destroy', 'show']);

 
    /* ROTA: FUNCIONARIO
    * funcionario => POST(store), GET(index) 
    * funcionario/create => GET(create) 
    * funcionario/{id} => PUT(update)
    */
    Route::resource('fornecedor', 'FornecedorController')->except(['edit', 'destroy', 'show']);
   
    /* ROTA: INSUMO
    * insumo => POST(store), GET(index) 
    * insumo/create => GET(create) 
    * insumo/{id} => PUT(update)
    */
    Route::resource('insumo', 'Insumo\InsumoController')->except(['edit', 'show', 'destroy']);

    /* ROTA: TIPO INSUMO
    * tipoinsumo => POST(store), GET(index) 
    * tipoinsumo/create => GET(create) 
    * tipoinsumo/{id} => GET(show), PUT(update), DELETE(destroy)
    * tipoinsumo/{id}/edit => GET(edit)
    */
    Route::resource('tipoinsumo', 'Insumo\TipoInsumoController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: GRUPO ANIMAL
    * grupoanimal => POST(store), GET(index) 
    * grupoanimal/create => GET(create) 
    * grupoanimal/{id} => GET(show), PUT(update), DELETE(destroy)
    * grupoanimal/{id}/edit => GET(edit)
    */
    Route::resource('grupoanimal', 'Animal\GrupoAnimalController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: TIPO MEDICAMENTO
    * tipomedicamento => POST(store), GET(index) 
    * tipomedicamento/create => GET(create) 
    * tipomedicamento/{id} => GET(show), PUT(update), DELETE(destroy)
    * tipomedicamento/{id}/edit => GET(edit)
    */
    Route::resource('tipomedicamento', 'Animal\TipoMedicamentoController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: MEDICAMENTO
    * medicamento => POST(store), GET(index) 
    * medicamento/create => GET(create) 
    * medicamento/{id} => PUT(update)
    */
    Route::resource('medicamento', 'Animal\MedicamentoController')->except(['edit', 'show', 'destroy']);

    /* ROTA: MÁQUINA
    * maquina => POST(store), GET(index) 
    * maquina/create => GET(create) 
    * maquina/{id} => PUT(update)
    */
    Route::resource('maquina', 'Maquina\MaquinaController')->except(['edit', 'show', 'destroy']);

    /* ROTA: HISTÓRICO ABASTECIMENTO (para saída de combustível)
    * abastecimento => POST(store), GET(index) 
    * abastecimento/create => GET(create) 
    * abastecimento/{id} => DELETE(destroy)
    */
    Route::resource('abastecimento', 'Maquina\HistoricoAbastecimentoController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO ANIMAL (para saída de medicamento)
    * medicacao => POST(store), GET(index) 
    * medicacao/create => GET(create) 
    * medicacao/{id} => DELETE(destroy)
    */
    Route::resource('medicacao', 'Animal\HistoricoAnimalController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO TERRA (para saída de insumo e uso na terra)
    * plantio => POST(store), GET(index) 
    * plantio/create => GET(create) 
    * plantio/{id} => DELETE(destroy)
    */
    Route::resource('plantio', 'Insumo\HistoricoTerraController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA COMBUSTÍVEL
    * compra-combustivel => POST(store), GET(index) 
    * compra-combustivel/create => GET(create) 
    * compra-combustivel/{id} => DELETE(destroy)
    */
    Route::resource('compra-combustivel', 'Maquina\HistoricoCompraCombustivelController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA INSUMO
    * compra-insumo => POST(store), GET(index) 
    * compra-insumo/create => GET(create) 
    * compra-insumo/{id} => DELETE(destroy)
    */
    Route::resource('compra-insumo', 'Insumo\HistoricoCompraInsumoController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA MEDICAMENTO
    * compra-medicamento => POST(store), GET(index) 
    * compra-medicamento/create => GET(create) 
    * compra-medicamento/{id} => DELETE(destroy)
    */
    Route::resource('compra-medicamento', 'Animal\HistoricoCompraMedicamentoController')->except(['show', 'update', 'edit']);

    /* ROTA: COMBUSTÍVEL
    * combustivel => POST(store), GET(index) 
    * combustivel/create => GET(create) 
    * combustivel/{id} => DELETE(destroy)
    */
    Route::resource('combustivel', 'Maquina\CombustivelController')->except(['show', 'update', 'destroy', 'edit']);
    
    /* ROTA: REVISÃO
    * revisao => POST(store), GET(index) 
    * revisao/create => GET(create) 
    * revisao/{id} => DELETE(destroy)
    */
    Route::resource('revisao', 'Maquina\HistoricoRevisaoController')->except(['show', 'update', 'edit']);
});

resources/views/entrada/ecombustivel.blade.php
 @extends('layouts.layout') @section('content')
<div class="container ">
	<!--Cabeçalho pagina-->
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Entrada de combustível</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Registrado!</strong> A entrada de combustível foi registrada no histórico.
			</div>
			@endif @if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>
	<!--/Cabeçalho pagina-->

	<!--Conteudo da pagina-->
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Dados da compra
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">

							<form name="armazenar" action="{{ route('compra-combustivel.store') }}" method="post">
								{{ csrf_field() }}
								<div class="row">
									<div class="col-md-8">

										<div class="form-group">
											<label>Fazenda:</label>
											<select id="fazendas" name="id_fazenda" required class="form-control" onchange="EntradaCombustivel()">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
												@foreach($fazendas as $fazenda)
												<option data-id="{{$fazenda}}" value="{{$fazenda->id}}">{{$fazenda->nome}}</option>
												@endforeach
											</select>
										</div>

										<div class="form-group">
											<label>Funcionário:</label>
											<select id="funcionario" required class="form-control" name="id_funcionario">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
											</select>
										</div>

										<div class="form-group">
											<label>Fornecedor:</label>
											<select name="id_fornecedor" required class="form-control">
												<option value="" selected>- Selecione o Fornecedor -</option>
												@foreach($fornecedores as $fornecedor) @if (old('id_fornecedor') == $fornecedor->id)
												<option value="{{$fornecedor->id}}" selected>{{$fornecedor->nome}}</option>
												@else
												<option value="{{$fornecedor->id}}">{{$fornecedor->nome}}</option>
												@endif @endforeach
											</select>
										</div>

										<div class="form-group">
											<label>Quantidade:</label>
											<input class="form-control" name="quantidade" required type="number" placeholder="Em litros" value="{{ old('quantidade')}}" />
										</div>

										<div class="form-group">
											<label>Data da compra:</label>
											<input class="form-control" name="data" type="date" required placeholder="DD/MM/AAAA" value="{{ old('data')}}" />
										</div>

										<div class="form-group">
											<label>Lote:</label>
											<input class="form-control" name="lote" placeholder="Lote de compra" maxlength="45" value="{{ old('lote')}}" />
										</div>

										<div class="form-group">
											<label>Nota fiscal:</label>
											<input class="form-control" name="nota_fiscal" required placeholder="Nota fiscal da compra" maxlength="45" value="{{ old('nota_fiscal')}}"
											/>
										</div>

										<div class="form-group">
											<label>Valor:</label>
											<input class="form-control" name="valor" required type="number" step=".01" placeholder="Valor da compra" value="{{ old('valor')}}" />
										</div>

									</div>
								</div>

								<div class="right-div">
									<button type="submit" class="btn btn-info pull-right">Salvar </button>
								</div>
								<div class="right-div">
									<button type="reset" class="btn btn-info pull-right">Limpar </button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--/Conteudo da pagina-->
</div>
</div>
@endsection

resources/views/entrada/efarmacia.blade.php
 @extends('layouts.layout') @section('content')
<script>
	function AddRow() {
		var tbl = document.getElementById('myTable').getElementsByTagName('tbody')[0];
		var tr = tbl.insertRow();

		fazenda = JSON.parse($("#fazendas").val());
		medicamentos = fazenda.medicamentos;

		//Célula de medicameto
		var td = tr.insertCell();
		var mdt = document.createElement("select");
		mdt.required = true;
		mdt.name = "id_medicamento[]";
		if (!$.isEmptyObject(medicamentos)) {
			for (var i in medicamentos) {
				var el = document.createElement("option");
				el.textContent = medicamentos[i].nome + " | Tipo do Medicamento: " + medicamentos[i].tipo_medicamento.nome;
				el.value = medicamentos[i].id;
				mdt.appendChild(el);
			}
		} else {
			var el = document.createElement("option");
			el.textContent = 'Vazio';
			el.value = '';
			mdt.appendChild(el);
		}
		td.appendChild(mdt);

		//Célula de quantidade
		var td = tr.insertCell();
		var qtd = document.createElement("input");
		qtd.type = "number";
		qtd.step = "0.01";
		qtd.required = true;
		qtd.onchange = function () {
			var row = document.getElementById("myTable").rows[tr.rowIndex];
			var quantidade = row.cells[1].children[0].value;
			var ml = row.cells[2].children[0].value;
			if (ml == "")
				if (quantidade == "")
					row.cells[3].children[0].value = "";
				else
					row.cells[3].children[0].value = quantidade;
			else
				row.cells[3].children[0].value = quantidade * ml;
		}
		td.appendChild(qtd);

		//Célula de ml
		var td = tr.insertCell();
		var ml = document.createElement("input");
		ml.type = "number";
		ml.onchange = function () {
			var row = document.getElementById("myTable").rows[tr.rowIndex];
			var quantidade = row.cells[1].children[0].value;
			var ml = row.cells[2].children[0].value;
			if (quantidade == "")
				row.cells[3].children[0].value = "";
			else
			if (ml == "")
				row.cells[3].children[0].value = quantidade;
			else
				row.cells[3].children[0].value = quantidade * ml;
		}
		td.appendChild(ml);

		//Célula de cálculo
		var td = tr.insertCell();
		var total = document.createElement("input");
		total.name = 'quantidade[]';
		total.readOnly = true;
		td.appendChild(total);

		//Botão de excluir 
		var td = tr.insertCell();
		var span = document.createElement('span');
		span.classList.add('table-remove', 'glyphicon', 'glyphicon-remove');
		span.onclick = function deleteRow() {
			document.getElementById("myTable").deleteRow(tr.rowIndex);
		}
		td.appendChild(span);
	}
</script>
<div class="container">
	<!--Cabeçalho pagina-->
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Entrada de Medicamentos</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Registrado!</strong> A entrada de medicamento foi registrada no histórico.
			</div>
			@endif @if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>
	<!--/Cabeçalho pagina-->

	<!--Conteudo da pagina-->
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Dados da compra
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">

							<form name="armazenar" action="{{ route('compra-medicamento.store') }}" method="post">
								{{ csrf_field() }}
								<div class="row">
									<div class="col-md-8">

										<div class="form-group">
											<label>Fazenda:</label>
											<select type="hidden" id="fazendas" required class="form-control" onchange="EntradaMedicamento()">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
												@foreach($fazendas as $fazenda)
												<option value="{{$fazenda}}">{{$fazenda->nome}}</option>
												@endforeach
											</select>
										</div>

										<div class="form-group" style="display: none;" id="div_funcionario">
											<label>Funcionário:</label>
											<select id="funcionario" required class="form-control" name="id_funcionario">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
											</select>
										</div>

										<div class="form-group">
											<label>Fornecedor:</label>
											<select type="hidden" name="id_fornecedor" required class="form-control" onchange="EntradaMedicamento()">
												@foreach($fornecedores as $fornecedor) @if(old('id_fornecedor') == $fornecedor->id)
												<option value="{{$fornecedor->id}}" selected>{{$fornecedor->nome}}</option>
												@else
												<option value="{{$fornecedor->id}}">{{$fornecedor->nome}}</option>
												@endif @endforeach
											</select>
										</div>

										<div class="form-group">
											<label>Data da Compra:</label>
											<input class="form-control" name="data" required type="date" placeholder="DD/MM/AAAA" value="{{ old('data')}}" />
										</div>

										<div class="form-group">
											<label>Nota Fiscal:</label>
											<input class="form-control" type="text" required name="nota_fiscal" placeholder="Número da nota fiscal da compra" value="{{ old('nota_fiscal')}}"
											/>
										</div>

										<div class="form-group">
											<label>Lote:</label>
											<input class="form-control" type="text" name="lote" placeholder="Número do lote" value="{{ old('lote')}}" />
										</div>

										<div class="form-group">
											<label>Valor:</label>
											<input class="form-control" type="text" name="valor" required placeholder="Em R$" value="{{ old('valor')}}" />
										</div>

										<div style="display: none;" class="form-group table-responsive" id="produtos">
											<label>Produtos da nota:</label>

											<table class="tableprod table-striped table-bordered table-hover" id="myTable">
												<thead>
													<tr>
														<th>Medicamento</th>
														<th>Qtd</th>
														<th>Ml (opcional)</th>
														<th>Total</th>
														<th></th>
													</tr>
												</thead>
												<tbody>
												</tbody>
											</table>

											<span class="table-add glyphicon glyphicon-plus" onclick="AddRow()"></span>

										</div>
									</div>
								</div>

								<div class="right-div">
									<button type="submit" class="btn btn-info pull-right">Salvar </button>
								</div>
								<div class="right-div">
									<button type="reset" class="btn btn-info pull-right">Limpar </button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/entrada/einsumo.blade.php
 @extends('layouts.layout') @section('content')
<script>
	function AddRow() {
		var tbl = document.getElementById('myTable').getElementsByTagName('tbody')[0];
		var tr = tbl.insertRow();

		fazenda = JSON.parse($("#fazendas").val());
		insumos = fazenda.insumos;

		//Célula de medicameto
		var td = tr.insertCell();
		var mdt = document.createElement("select");
		mdt.required = true;
		mdt.name = "id_insumo[]";

		if (!$.isEmptyObject(insumos)) {
			for (var i in insumos) {
				var el = document.createElement("option");
				el.textContent = insumos[i].nome + " | Tipo do Medicamento: " + insumos[i].tipo_insumo.nome;
				el.value = insumos[i].id;
				mdt.appendChild(el);
			}
		} else {
			var el = document.createElement("option");
			el.textContent = 'Vazio';
			el.value = '';
			mdt.appendChild(el);
		}
		td.appendChild(mdt);

		//Célula de quantidade
		var td = tr.insertCell();
		var qtd = document.createElement("input");
		qtd.name = "quantidade[]";
		qtd.type = "number";
		qtd.step = "0.01";
		qtd.required = true;
		td.appendChild(qtd);

		//Botão de excluir 
		var td = tr.insertCell();
		var span = document.createElement("span");
		span.classList.add('table-remove', 'glyphicon', 'glyphicon-remove');
		span.onclick = function deleteRow() {
			document.getElementById("myTable").deleteRow(tr.rowIndex);
		}
		td.appendChild(span);
	}
</script>
<div class="container">
	<!--Cabeçalho pagina-->
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Entrada de Insumo</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Registrado!</strong> A entrada de insumo foi registrada no histórico.
			</div>
			@endif @if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>
	<!--/Cabeçalho pagina-->

	<!--Conteudo da pagina-->
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Informações da compra
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">

							<form name="armazenar" action="{{ route('compra-insumo.store') }}" method="post">
								{{ csrf_field() }}
								<div class="row">
									<div class="col-md-8">

										<div class="form-group">
											<label>Fazenda:</label>
											<select type="hidden" id="fazendas" required class="form-control" onchange="EntradaInsumo()">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
												@foreach($fazendas as $fazenda)
												<option value="{{$fazenda}}">{{$fazenda->nome}}</option>
												@endforeach
											</select>
										</div>

										<div class="form-group" style="display: none;" id="div_funcionario">
											<label>Funcionário:</label>
											<select id="funcionario" required class="form-control" name="id_funcionario">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
											</select>
										</div>

										<div class="form-group">
											<label>Fornecedor:</label>
											<select type="hidden" name="id_fornecedor" required class="form-control" onchange="EntradaMedicamento()">
												@foreach($fornecedores as $fornecedor) @if(old('id_fornecedor') == $fornecedor->id)
												<option value="{{$fornecedor->id}}" selected>{{$fornecedor->nome}}</option>
												@else
												<option value="{{$fornecedor->id}}">{{$fornecedor->nome}}</option>
												@endif @endforeach
											</select>
										</div>

										<div class="form-group">
											<label>Data da Compra:</label>
											<input class="form-control" name="data" type="date" required placeholder="DD/MM/AAAA" value="{{ old('data')}}" />
										</div>

										<div class="form-group">
											<label>Nota Fiscal:</label>
											<input class="form-control" type="text" name="nota_fiscal" required placeholder="Número da nota da compra" value="{{ old('nota_fiscal')}}"
											/>
										</div>

										<div class="form-group">
											<label>Lote:</label>
											<input class="form-control" type="text" name="lote" placeholder="Número do lote (Opcional)" value="{{ old('lote')}}" />
										</div>

										<div class="form-group">
											<label>Valor:</label>
											<input class="form-control" required type="number" step=".01" name="valor" placeholder="Em R$" value="{{ old('valor')}}"
											/>
										</div>

										<div style="display: none;" class="form-group table-responsive" id="produtos">
											<label>Produtos da nota:</label>
											<table class="tableprod table-striped table-bordered table-hover" id="myTable">
												<thead>
													<tr>
														<th>Insumo</th>
														<th>Qtd</th>
														<th></th>
													</tr>
												</thead>
												<tbody>
												</tbody>
											</table>

											<span class="table-add glyphicon glyphicon-plus" onclick="AddRow()"></span>

										</div>
									</div>
								</div>

								<div class="right-div">
									<button type="submit" class="btn btn-info pull-right">Salvar </button>
								</div>
								<div class="right-div">
									<button type="reset" class="btn btn-info pull-right">Limpar </button>
								</div>
							</form>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/entrada/erevisao.blade.php
 @extends('layouts.layout') @section('content')
<div class="container ">
	<!--Cabeçalho pagina-->
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Revisão de Máquina</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Registrado!</strong> A entrada de revisão foi registrada.
			</div>
			@endif @if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>
	<!--/Cabeçalho pagina-->

	<!--Conteudo da pagina-->
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Dados sobre a revisão
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">

							<form name="armazenar" action="{{ route('revisao.store') }}" method="post">
								{{ csrf_field() }}
								<div class="row">
									<div class="col-md-8">

										<div class="form-group">
											<label>Fazenda:</label>
											<select id="fazendas" name="id_fazenda" required class="form-control" onchange="Maquinas()">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
												@foreach($fazendas as $fazenda)
													<option data-id="{{$fazenda}}" value="{{$fazenda->id}}">{{$fazenda->nome}}</option>
												@endforeach
											</select>
										</div>

										<div class="form-group">
											<label>Funcionário:</label>
											<select id="funcionario" required class="form-control" name="id_funcionario">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
											</select>
										</div>

										<div class="form-group">
											<label>Máquina:</label>
											<select id="maquina" required class="form-control" name="id_maquina">
												<option value="" disabled selected>- Selecione uma fazenda -</option>
											</select>
										</div>

										<div class="form-group">
											<label>Problema:</label>
											<textarea class="form-control" name="problema" required maxlength="190" style="resize: vertical"
											placeholder="Motivo da revisão" value="{{ old('problema')}}"></textarea>
										</div>

										<div class="form-group">
											<label>Data:</label>
											<input class="form-control" name="data" required type="date" placeholder="DD/MM/AAAA" value="{{ old('data')}}"/>
										</div>

										<div class="form-group">
											<label>Item:</label>
											<input class="form-control" name="item" placeholder="Item comprado (Opcional)" maxlength="45" value="{{ old('item')}}"/>
										</div>

										<div class="form-group">
											<label>Nota fiscal:</label>
											<input class="form-control" name="nota_fiscal" placeholder="Nota fiscal da compra (Opcional)" maxlength="45" value="{{ old('nota_fiscal')}}"/>
										</div>

										<div class="form-group">
											<label>Valor:</label>
											<input class="form-control" name="valor" type="numeric" placeholder="Valor da compra (Opcional)" value="{{ old('valor')}}"/>
										</div>

									</div>
								</div>

								<div class="right-div">
									<button type="submit" class="btn btn-info pull-right">Salvar </button>
								</div>
								<div class="right-div">
									<button type="reset" class="btn btn-info pull-right">Limpar </button>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>
@endsection