routes/web.php
<?php

//Rotas de início
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Rotas autenticadas
Route::group(['middleware' => 'auth'], function()
{
    /* ROTA: ANIMAIS
    * animais => POST(store), GET(index) 
    * animais/create => GET(create) 
    * animais/{id} => PUT(update)
    */
    Route::resource('animal', 'Animal\AnimalController')->except(['show', 'edit', 'destroy']);
    /* ROTA: FAZENDAS
    * fazendas => POST(store), GET(index) 
    * fazendas/create => GET(create) 
    * fazendas/{id} => DELETE(destroy)
    */ 
    Route::resource('fazenda', 'Fazenda\FazendaController')->except(['edit', 'show', 'destroy']);

    /* ROTA: TERRA
    * terra => POST(store), GET(index) 
    * terra/create => GET(create) 
    * terra/{id} => PUT(update)
    */
    Route::resource('terra', 'Insumo\TerraController')->except(['edit', 'show', 'destroy']);

    /* ROTA: FUNCIONARIO
    * funcionario => POST(store), GET(index) 
    * funcionario/create => GET(create) 
    * funcionario/{id} => GET(show), PUT(update), DELETE(destroy)
    * funcionario/{id}/edit => GET(edit)
    */
    Route::resource('funcionario', 'Funcionario\FuncionarioController')->except(['edit', 'destroy', 'show']);

 
    /* ROTA: FUNCIONARIO
    * funcionario => POST(store), GET(index) 
    * funcionario/create => GET(create) 
    * funcionario/{id} => PUT(update)
    */
    Route::resource('fornecedor', 'FornecedorController')->except(['edit', 'destroy', 'show']);
   
    /* ROTA: INSUMO
    * insumo => POST(store), GET(index) 
    * insumo/create => GET(create) 
    * insumo/{id} => PUT(update)
    */
    Route::resource('insumo', 'Insumo\InsumoController')->except(['edit', 'show', 'destroy']);

    /* ROTA: TIPO INSUMO
    * tipoinsumo => POST(store), GET(index) 
    * tipoinsumo/create => GET(create) 
    * tipoinsumo/{id} => GET(show), PUT(update), DELETE(destroy)
    * tipoinsumo/{id}/edit => GET(edit)
    */
    Route::resource('tipoinsumo', 'Insumo\TipoInsumoController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: GRUPO ANIMAL
    * grupoanimal => POST(store), GET(index) 
    * grupoanimal/create => GET(create) 
    * grupoanimal/{id} => GET(show), PUT(update), DELETE(destroy)
    * grupoanimal/{id}/edit => GET(edit)
    */
    Route::resource('grupoanimal', 'Animal\GrupoAnimalController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: TIPO MEDICAMENTO
    * tipomedicamento => POST(store), GET(index) 
    * tipomedicamento/create => GET(create) 
    * tipomedicamento/{id} => GET(show), PUT(update), DELETE(destroy)
    * tipomedicamento/{id}/edit => GET(edit)
    */
    Route::resource('tipomedicamento', 'Animal\TipoMedicamentoController')->except(['show', 'update', 'edit', 'destroy', 'index']);

    /* ROTA: MEDICAMENTO
    * medicamento => POST(store), GET(index) 
    * medicamento/create => GET(create) 
    * medicamento/{id} => PUT(update)
    */
    Route::resource('medicamento', 'Animal\MedicamentoController')->except(['edit', 'show', 'destroy']);

    /* ROTA: MÁQUINA
    * maquina => POST(store), GET(index) 
    * maquina/create => GET(create) 
    * maquina/{id} => PUT(update)
    */
    Route::resource('maquina', 'Maquina\MaquinaController')->except(['edit', 'show', 'destroy']);

    /* ROTA: HISTÓRICO ABASTECIMENTO (para saída de combustível)
    * abastecimento => POST(store), GET(index) 
    * abastecimento/create => GET(create) 
    * abastecimento/{id} => DELETE(destroy)
    */
    Route::resource('abastecimento', 'Maquina\HistoricoAbastecimentoController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO ANIMAL (para saída de medicamento)
    * medicacao => POST(store), GET(index) 
    * medicacao/create => GET(create) 
    * medicacao/{id} => DELETE(destroy)
    */
    Route::resource('medicacao', 'Animal\HistoricoAnimalController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO TERRA (para saída de insumo e uso na terra)
    * plantio => POST(store), GET(index) 
    * plantio/create => GET(create) 
    * plantio/{id} => DELETE(destroy)
    */
    Route::resource('plantio', 'Insumo\HistoricoTerraController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA COMBUSTÍVEL
    * compra-combustivel => POST(store), GET(index) 
    * compra-combustivel/create => GET(create) 
    * compra-combustivel/{id} => DELETE(destroy)
    */
    Route::resource('compra-combustivel', 'Maquina\HistoricoCompraCombustivelController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA INSUMO
    * compra-insumo => POST(store), GET(index) 
    * compra-insumo/create => GET(create) 
    * compra-insumo/{id} => DELETE(destroy)
    */
    Route::resource('compra-insumo', 'Insumo\HistoricoCompraInsumoController')->except(['show', 'update', 'edit']);

    /* ROTA: HISTÓRICO COMPRA MEDICAMENTO
    * compra-medicamento => POST(store), GET(index) 
    * compra-medicamento/create => GET(create) 
    * compra-medicamento/{id} => DELETE(destroy)
    */
    Route::resource('compra-medicamento', 'Animal\HistoricoCompraMedicamentoController')->except(['show', 'update', 'edit']);

    /* ROTA: COMBUSTÍVEL
    * combustivel => POST(store), GET(index) 
    * combustivel/create => GET(create) 
    * combustivel/{id} => DELETE(destroy)
    */
    Route::resource('combustivel', 'Maquina\CombustivelController')->except(['show', 'update', 'destroy', 'edit']);
    
    /* ROTA: REVISÃO
    * revisao => POST(store), GET(index) 
    * revisao/create => GET(create) 
    * revisao/{id} => DELETE(destroy)
    */
    Route::resource('revisao', 'Maquina\HistoricoRevisaoController')->except(['show', 'update', 'edit']);
});

resources/views/cadastro/canimal.blade.php
 @extends('layouts.layout') @section('content')
<div class="container">
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Cadastrar Animais</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Cadastrado!</strong> O animal foi armazenado.
			</div>
			@endif @if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Cadastre o animal inserindo-o nos campos abaixo:
				</div>

				<form name="register-animal" action="{{ route('animal.store') }}" method="post">
					{{ csrf_field() }}
					<div class="panel-body">
						<div class="row">
							<div class="col-md-8">

								<div class="form-group">
									<label>Fazenda:</label>
									<select class="form-control" name="id_fazenda" required/>
									<option value="" disabled selected>- Selecione uma fazenda -</option>
									@foreach($fazendas as $fazenda) @if (old('id_fazenda') == $fazenda->id)
									<option value="{{$fazenda->id}}" selected>{{$fazenda->nome}}</option>
									@else
									<option value="{{$fazenda->id}}">{{$fazenda->nome}}</option>
									@endif @endforeach
									</select>
								</div>

								<div class="form-group">
									<label>Nome:</label>
									<input class="form-control" name="nome" required type="text" placeholder="Identificação do animal" maxlength="45" value="{{ old('nome')}}"
									/>
								</div>

								<div class="form-group">
									<label>Grupo do animal:</label>
									<select class="form-control" name="id_grupo_animal">
										<option value="" disabled selected>- Selecione um grupo de animal -</option>
										@foreach($grupos as $item)
										<option value="{{$item->id}}">{{$item->nome}}</option>
										@endforeach
									</select>
								</div>

								<div class="form-group">
									<label>Data de entrada:</label>
									<input class="form-control" name="entrada" required type="date" placeholder="DD/MM/AAAA" maxlength="45" value="{{ old('entrada')}}"
									/>
								</div>

								<div class="form-group">
									<label>Data de Nascimento:</label>
									<input class="form-control" name="nascimento" type="date" placeholder="DD/MM/AAAA" maxlength="45" value="{{ old('nascimento')}}"
									/>
								</div>

								<div class="form-group">
									<label>Identificão da mãe:</label>
									<input class="form-control" name="nome_mae" type="text" placeholder="Nome da mãe" maxlength="45" value="{{ old('nome_mae')}}"
									/>
								</div>

								<div class="form-group">
									<label>Identificão do pai:</label>
									<input class="form-control" name="nome_pai" type="text" placeholder="Nome do pai" maxlength="45" value="{{ old('nome_pai')}}"
									/>
								</div>
							</div>

							<div class="col-md-12">
								<div class="right-div">
									<button type="submit" class="btn btn-info pull-right">Salvar </button>
								</div>
								<div class="right-div">
									<button type="reset" class="btn btn-info pull-right">Limpar </button>
								</div>
							</div>

						</div>
					</div>
				</form>

			</div>
		</div>
	</div>
	
</div>
</div>
@endsection

resources/views/cadastro/cfarmacia.blade.php
@extends('layouts.layout') @section('content')
<div class="container">
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Cadastrar Medicamentos</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Cadastrado!</strong> O medicamento foi armazenado.
			</div>
			@endif @if ($errors->any()) @foreach ($errors->all() as $error)
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$error}}.
			</div>
			@endforeach @endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Cadastre o medicamento inserindo-o nos campos abaixo:
				</div>
				<form name="register-medicamentos" action="{{ route('medicamento.store') }}" method="post">
					{{ csrf_field() }}
					<div class="panel-body">
						<div class="row">
							<div class="col-md-12">

								<div class="row">
									<div class="col-md-8">
										<div class="form-group">
											<label>Fazenda:</label>
											<select class="form-control" name="id_fazenda" required>
												<option value="" disabled selected>- Selecione uma fazenda -</option>
												@foreach($fazendas as $fazenda) @if (old('id_fazenda') == $fazenda->id)
												<option value="{{$fazenda->id}}" selected>{{$fazenda->nome}}</option>
												@else
												<option value="{{$fazenda->id}}">{{$fazenda->nome}}</option>
												@endif @endforeach
											</select>
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col-md-8">
										<div class="form-group">
											<label>Nome:</label>
											<input class="form-control" name="nome" required type="text" placeholder="Nome do medicamento" maxlength="45" value="{{ old('nome')}}" />
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col-md-8">
										<div class="form-group">
											<label>Tipo de medicamento:</label>
											<select class="form-control" name="id_tipo_medicamento">
												<option value="" disabled selected>- Selecione um tipo de medicamento -</option>
												@foreach($tipos as $tipo) @if (old('id_tipo_medicamento') == $tipo->id)
												<option value="{{$tipo->id}}" selected>{{$tipo->nome}}</option>
												@else
												<option value="{{$tipo->id}}">{{$tipo->nome}}</option>
												@endif @endforeach
											</select>
										</div>
									</div>
								</div>

								<div class="row">
									<div class="col-md-8">
										<div class="form-group">
											<label>Observações:</label>
											<input class="form-control" name="obs" type="text" placeholder="Observações a respeito do medicamento" maxlength="140" value="{{ old('obs')}}" />
										</div>
									</div>
								</div>

								<div class="right-div">
									<button type="submit" class="btn btn-info pull-right">Salvar </button>
								</div>
								<div class="right-div">
									<button type="reset" class="btn btn-info pull-right">Limpar </button>
								</div>

							</div>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/cadastro/cfazenda.blade.php
 @extends('layouts.layout')
 @section('content')

<div class="container">
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Cadastrar Fazenda</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Cadastrada!</strong> A fazenda foi armazenada.
			</div>
			@endif
			@if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Insira os dados para cadastrar uma fazenda:
				</div>

				<form name="register-fazenda" action="{{ route('fazenda.store')}}" method="post">
					{{ csrf_field() }}
					<div class="panel-body">
						<div class="row">
							<div class="col-md-12">

								<div class="col-md-8">
									<div class="form-group">
										<label>Nome da fazenda:</label>
										<input class="form-control" type="text" name="nome" required maxlength="100" placeholder="Insira aqui o nome da sua fazenda" maxlength="100" value="{{ old('nome')}}"/>
									</div>
								</div>

								<div class="col-md-5">
									<div class="form-group">
										<label>Localidade:</label>
										<input class="form-control" type="text" name="localidade" maxlength="45" placeholder="Insira aqui o local da sua fazenda" maxlength="45" value="{{ old('localidade')}}"/>
									</div>
								</div>

							</div>

							<div class="right-div">
								<button type="submit" class="btn btn-info pull-right">Salvar </button>
							</div>
							<div class="right-div">
								<button type="reset" class="btn btn-info pull-right">Limpar </button>
							</div>

						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/cadastro/cfornecedor.blade.php
 @extends('layouts.layout')
 @section('content')

<div class="container">
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Cadastrar Fornecedor</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Cadastrado!</strong> O fornecedor foi armazenado.
			</div>
			@endif
			@if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Insira os dados para cadastrar um fornecedor:
				</div>

				<form name="register-fornecedor" action="{{ route('fornecedor.store')}}" method="post">
					{{ csrf_field() }}
					<div class="panel-body">
						<div class="row">
							<div class="col-md-12">

								<div class="col-md-8">
									<div class="form-group">
										<label>Nome:</label>
										<input class="form-control" type="text" required maxlength="45" name="nome" placeholder="Insira aqui o nome do fornecedor" maxlength="45" value="{{ old('nome')}}"/>
									</div>
								</div>

								<div class="col-md-8">
									<div class="form-group">
										<label>Telefone:</label>
										<input class="form-control" type="text" required name="telefone" placeholder="(__)____-____" maxlength="45" value="{{ old('telefone')}}"/>
									</div>
								</div>

							</div>

							<div class="right-div">
								<button type="submit" class="btn btn-info pull-right">Salvar </button>
							</div>
							<div class="right-div">
								<button type="reset" class="btn btn-info pull-right">Limpar </button>
							</div>

						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
</div>
@endsection

resources/views/cadastro/cfuncionario.blade.php
 @extends('layouts.layout') @section('content')

<div class="container">
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Cadastrar Funcionários</h3>
			@if (session()->has('success'))
			<div class="alert alert-success alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Cadastrado!</strong> O funcionário foi armazenado.
			</div>
			@endif @if ($errors->any())
			<div class="alert alert-warning alert-dismissible">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Ops!</strong> {{$errors->first()}}.
			</div>
			@endif
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Insira os dados para cadastrar um funcionário:
				</div>
				<form name="register-funcionario" action="{{ route('funcionario.store') }}" method="post">
					{{ csrf_field() }}
					<div class="panel-body">

						<div class="form-group">
							<label>Fazenda:</label>
							<div class="form-group">
								<select class="form-control" name="id_fazenda" required>
									<option value="" disabled selected>- Selecione uma fazenda -</option>
									@foreach($fazendas as $fazenda) @if (old('id_fazenda') == $fazenda->id)
									<option value="{{$fazenda->id}}" selected>{{$fazenda->nome}}</option>
									@else
									<option value="{{$fazenda->id}}">{{$fazenda->nome}}</option>
									@endif @endforeach
								</select>
							</div>
						</div>

						<div class="row">
							<div class="col-md-4">
								<div class="form-group">
									<label>Nome:</label>
									<input class="form-control" name="nome" required maxlength="100" type="text" placeholder="Insira aqui o nome completo do funcionário"
									    maxlength="100" value="{{ old('nome')}}" />
								</div>
								<div class="form-group">
									<label>RG:</label>
									<input class="form-control" name="rg" type="text" required maxlength="45" placeholder="Insira aqui o RG do funcionário" maxlength="45"
									    value="{{ old('rg')}}" />
								</div>
								<div class="form-group">
									<label>Estado Civil:</label>
									<div class="form-group">
										<select class="form-control" required name="id_estado_civil">
											<option value="" disabled selected>- Selecione um estado civil -</option>
											@foreach($grupos as $item)
											<option value="{{$item->id}}">{{$item->nome}}</option>
											@endforeach
										</select>
									</div>
								</div>
								<div class="form-group">
									<label>Rua:</label>
									<input class="form-control" type="text" name="endereco_rua" required maxlength="45" placeholder="Insira aqui o endereço do funcionário"
									    maxlength="45" value="{{ old('endereco_rua')}}" />
								</div>
								<div class="form-group">
									<label>Bairro:</label>
									<input class="form-control" type="text" name="endereco_bairro" required maxlength="45" placeholder="Insira aqui o bairro do funcionário"
									    maxlength="45" value="{{ old('endereco_bairro')}}" />
								</div>
								<div class="form-group">
									<label>País:</label>
									<input class="form-control" name="endereco_pais" type="text" required maxlength="45" placeholder="Insira aqui o país do funcionário"
									    maxlength="45" value="{{ old('endereco_pais')}}" />
								</div>
							</div>

							<div class="col-md-4">
								<div class="form-group">
									<label>Sexo:</label>
									<div class="radio">
										<div class="col-md-4">
											<label>
												<input type="radio" name="sexo" id="optionsRadios1" value="feminino" {{(old( 'sexo')=='feminino' ) ? 'checked' : '' }}>Feminino
											</label>
										</div>
										<div class="col-md-6">
											<label>
												<input type="radio" name="sexo" id="optionsRadios1" value="masculino" {{ (old( 'sexo')=='masculino' ) ? 'checked' : '' }}>Masculino
											</label>
										</div>
									</div>
								</div>
								<div class="form-group">
									<label>CPF:</label>
									<input class="form-control" name="cpf" type="text" required placeholder="Insira aqui o CPF" maxlength="45" value="{{ old('cpf')}}"
									/>
								</div>
								<div class="form-group">
									<label>Data de Nascimento:</label>
									<input class="form-control" name="nascimento" type="date" required placeholder="DD/MM/AAAA" maxlength="45" value="{{ old('nascimento')}}"
									/>
								</div>
								<div class="form-group">
									<label>Nº:</label>
									<input class="form-control" name="endereco_numero" type="text" required placeholder="Insira aqui o número da casa" maxlength="45"
									    value="{{ old('endereco_numero')}}" />
								</div>
								<div class="form-group">
									<label>Cidade:</label>
									<input class="form-control" name="endereco_cidade" type="text" required placeholder="Insira aqui a cidade do funcionário"
									    maxlength="45" value="{{ old('endereco_cidade')}}" />
								</div>
								<div class="form-group">
									<label>Cargo:</label>
									<input class="form-control" type="text" name="cargo" required placeholder="Insira aqui a função do funcionário" maxlength="45"
									    value="{{ old('cargo')}}" />
								</div>
							</div>

							<div class="col-md-4">
								<div class="form-group">
									<label>PIS:</label>
									<input class="form-control" name="pis" required type="text" placeholder="PIS do funcionário" maxlength="45" value="{{ old('pis')}}" />
								</div>
								<div class="form-group">
									<label>Telefone:</label>
									<input class="form-control" name="tel_fixo" required type="text" placeholder="(__)____-____" maxlength="45" value="{{ old('tel_fixo')}}"
									/>
								</div>
								<div class="form-group">
									<label>Celular:</label>
									<input class="form-control" name="celular" required type="text" placeholder="(__)_____-____" maxlength="45" value="{{ old('celular')}}"
									/>
								</div>
								<div class="form-group">
									<label>Estado:</label>
									<input class="form-control" name="endereco_estado" required type="text" placeholder="Insira aqui o estado" maxlength="45"
									    value="{{ old('endereco_estado')}}" />
								</div>
								<div class="form-group">
									<label>CEP:</label>
									<input class="form-control" name="cep" required type="text" placeholder="CEP" maxlength="45" value="{{ old('cep')}}" />
								</div>
								<div class="form-group">
									<label>Data de Admissão:</label>
									<input class="form-control" name="admissao" required type="date" placeholder="DD/MM/AAAA" maxlength="45" value="{{ old('admissao')}}"
									/>
								</div>
							</div>

							<div class="right-div">
								<button type="submit" class="btn btn-info pull-right">Salvar </button>
							</div>
							<div class="right-div">
								<button type="reset" class="btn btn-info pull-right">Limpar </button>
							</div>

						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
</div>
</div>
@endsection

resources/views/cadastro/cganimal.blade.php
 @extends('layouts.layout') @section('content')
<div class="container">
	<!--Cabeçalho pagina-->
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Grupo de Animal</h3>
				@if (session()->has('success'))
					<div class="alert alert-success alert-dismissible">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
						<strong>Cadastrado!</strong> O grupo de animal foi armazenado.
					</div>
				@endif
				@if ($errors->any())
					@foreach ($errors->all() as $error)
					<div class="alert alert-warning alert-dismissible">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
						<strong>Ops!</strong> {{$error}}.
					</div>
					@endforeach
				@endif
		</div>
	</div>
	<!--/Cabeçalho pagina-->

	<!--Conteudo da pagina-->
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Insira os dados para cadastrar um grupo de animal:
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">

							<form name="register-grupoanimal" action="{{ route('grupoanimal.store') }}" method="post">
								{{ csrf_field() }}
								<div class="row">
									<div class="col-md-8">
										<div class="form-group">
											<label>Nome:</label>
											<input class="form-control" type="text" required maxlength="45" name="nome" required placeholder="Insira aqui o nome do grupo" maxlength="45" value="{{ old('nome')}}"/>
										</div>
									</div>
								</div>

								<div class="right-div">
									<button type="submit" class="btn btn-info pull-right">Salvar </button>
								</div>
								<div class="right-div">
									<button type="reset" class="btn btn-info pull-right">Limpar </button>
								</div>
							</form>
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--/Conteudo da pagina-->
</div>
</div>
@endsection

resources/views/cadastro/ctinsumo.blade.php
 @extends('layouts.layout') @section('content')
<div class="container">
	<!--Cabeçalho pagina-->
	<div class="col-md-12">
		<div class="row pad-botm">
			<h3 class="header-line">Tipo de Insumo</h3>
				@if (isset($success))
					<div class="alert alert-success alert-dismissible">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
						<strong>Cadastrado!</strong> O tipo de insumo foi armazenado.
					</div>
				@endif
				@if ($errors->any())
					@foreach ($errors->all() as $error)
					<div class="alert alert-warning alert-dismissible">
						<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
						<strong>Ops!</strong> {{$error}}.
					</div>
					@endforeach
				@endif
		</div>
	</div>
	<!--/Cabeçalho pagina-->

	<!--Conteudo da pagina-->
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					Insira os dados para cadastrar um tipo de insumo:
				</div>
				<div class="panel-body">
					<div class="row">
						<div class="col-md-12">

							<form name="register-tipoinsumo" action="{{ route('tipoinsumo.store') }}" method="post">
								{{ csrf_field() }}
								<div class="row">
									<div class="col-md-8">
										<div class="form-group">
											<label>Nome:</label>
											<input class="form-control" type="text" name="nome" required placeholder="Insira aqui o nome do tipo do insumo" maxlength="45" value="{{ old('nome')}}"/>
										</div>
									</div>
								</div>

								<div class="right-div">
									<button type="submit" class="btn btn-info pull-right">Salvar </button>
								</div>
								<div class="right-div">
									<button type="reset" class="btn btn-info pull-right">Limpar </button>
								</div>
							</form>
							
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--/Conteudo da pagina-->
</div>
</div>
@endsection